[component]
name = "Arjm11d7502AbEw2"
title = "Abracon ARJM11 RJ45 Ethernet Connector with Magnetics, 10/100/1000 Base-T, PoE"
lib_id = "ARJM11D7-502-AB-EW2"
datasheet = "https://abracon.com/Magnetics/ARJM11.pdf"

[[pin]]
num = 1
number = "P3"
name = "TD2+"
purpose = "I/O"
kind = "dio"
pos = [3.175, -6.35]
rotation = 0.0
length = 1.458
width = 1.458
height = 1.458
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 0.95

[[pin]]
num = 2
number = "P1"
name = "TD1+"
purpose = "I/O"
kind = "dio"
pos = [5.715, -6.35]
rotation = 0.0
length = 1.458
width = 1.458
height = 1.458
pad_type = "thru_hole"
pad_shape = "rect"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 0.95

[[pin]]
num = 3
number = "P8"
name = "TD3-"
purpose = "I/O"
kind = "dio"
pos = [-3.175, -8.89]
rotation = 0.0
length = 1.458
width = 1.458
height = 1.458
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 0.95

[[pin]]
num = 4
number = "P5"
name = "CT_1"
purpose = "I/O"
kind = "dio"
pos = [0.635, -6.35]
rotation = 0.0
length = 1.458
width = 1.458
height = 1.458
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 0.95

[[pin]]
num = 5
number = "P12"
name = "~"
purpose = "I/O"
kind = "dio"
pos = [-6.785, 4.57]
rotation = 0.0
length = 1.605
width = 1.605
height = 1.605
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 1.07

[[pin]]
num = 6
number = "P11"
name = "~"
purpose = "I/O"
kind = "dio"
pos = [-6.785, 2.54]
rotation = 0.0
length = 1.605
width = 1.605
height = 1.605
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 1.07

[[pin]]
num = 7
number = "P2"
name = "TD1-"
purpose = "I/O"
kind = "dio"
pos = [4.445, -8.89]
rotation = 0.0
length = 1.458
width = 1.458
height = 1.458
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 0.95

[[pin]]
num = 8
number = "S1"
name = "SHIELD"
purpose = "I/O"
kind = "dio"
pos = [7.75, -3.05]
rotation = 0.0
length = 2.475
width = 2.475
height = 2.475
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 1.65

[[pin]]
num = 9
number = "S2"
name = "SHIELD"
purpose = "I/O"
kind = "dio"
pos = [-7.75, -3.05]
rotation = 0.0
length = 2.475
width = 2.475
height = 2.475
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 1.65

[[pin]]
num = 10
number = "P7"
name = "TD3+"
purpose = "I/O"
kind = "dio"
pos = [-1.905, -6.35]
rotation = 0.0
length = 1.458
width = 1.458
height = 1.458
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 0.95

[[pin]]
num = 11
number = "P14"
name = "~"
purpose = "I/O"
kind = "dio"
pos = [6.785, 4.57]
rotation = 0.0
length = 1.605
width = 1.605
height = 1.605
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 1.07

[[pin]]
num = 12
number = "P13"
name = "~"
purpose = "I/O"
kind = "dio"
pos = [6.785, 2.54]
rotation = 0.0
length = 1.605
width = 1.605
height = 1.605
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 1.07

[[pin]]
num = 13
number = "P9"
name = "TD4+"
purpose = "I/O"
kind = "dio"
pos = [-4.445, -6.35]
rotation = 0.0
length = 1.458
width = 1.458
height = 1.458
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 0.95

[[pin]]
num = 14
number = "P10"
name = "TD4-"
purpose = "I/O"
kind = "dio"
pos = [-5.715, -8.89]
rotation = 0.0
length = 1.458
width = 1.458
height = 1.458
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 0.95

[[pin]]
num = 15
number = "P4"
name = "TD2-"
purpose = "I/O"
kind = "dio"
pos = [1.905, -8.89]
rotation = 0.0
length = 1.458
width = 1.458
height = 1.458
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 0.95

[[pin]]
num = 16
number = "P6"
name = "CT_2"
purpose = "I/O"
kind = "dio"
pos = [-0.635, -8.89]
rotation = 0.0
length = 1.458
width = 1.458
height = 1.458
pad_type = "thru_hole"
pad_shape = "circle"
solder_mask_margin = 0.102
layers = "*.Cu *.Mask"
drill = 0.95

[[mechanical]]
pos = [5.715, 0.0]
width = 3.3
height = 3.3
pad_type = "np_thru_hole"
pad_shape = "circle"
layers = "*.Cu *.Mask"
drill = 3.3

[[mechanical]]
pos = [-5.715, 0.0]
width = 3.3
height = 3.3
pad_type = "np_thru_hole"
pad_shape = "circle"
layers = "*.Cu *.Mask"
drill = 3.3
